[fortuna] support env var in yaml config
pyth-network/pyth-crosschain pull request #1220
Opened 2024-01-10 16:29 UTC by 0xfirefist

2024-01-10 17:04 UTC, ali-bahjati commented on fortuna/src/config.rs
> +                Err(err) => {
why not return immediately with error?

2024-01-10 18:46 UTC, jayantk requested changes
I left a couple implementation suggestions here

One other note is that this feels complicated. What exactly are we trying to achieve here, and is there a simpler way to do it? 

I think you're trying to keep the API keys a secret? If so, can we do something simpler like put the whole config.yaml file in 1password?

Or is it such a big deal to put the API keys in the deployments repo? These aren't super sensitive, and I see there are some other API keys in there already.

2024-01-10 18:46 UTC, jayantk commented on fortuna/src/config.rs
> +        let config: Config = serde_yaml::from_str(&Config::inject_env(&yaml_content)?)?;
I think you should explicitly pass a map of substitutions into the `load` function and down into the config replacement. That will make these functions into pure functions (which are easy to test, use in other contexts, etc)

2024-01-10 18:46 UTC, jayantk commented on fortuna/src/config.rs
> +        let config: Config = serde_yaml::from_str(&Config::inject_env(&yaml_content)?)?;
this also forces you to make the dependencies of the code explicit instead of implicit

2024-01-11 11:11 UTC, 0xfirefist commented on fortuna/src/main.rs
> +    dotenv().ok();
I am thinking of a future state where we will need multiple env vars like 5-6. 
We don't need dotenv for deployments. We are not using .env file there. 

But for local development. I think it's better to have them in env file.

2024-01-11 13:26 UTC, closed without merging