[xc-admin] add permission/depermission publisher keys for all asset types
pyth-network/pyth-crosschain pull request #620
Opened 2023-02-22 05:47 UTC by cctdaniel

2023-02-22 09:16 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/components/PermissionDepermissionKey.tsx
> +        if (product.metadata.asset_type === selectedAssetType) {
This not handling the all case properly

2023-02-22 09:17 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/components/PermissionDepermissionKey.tsx
> +              .addPublisher(new PublicKey(publisherKey))
How do you plan on handling the case where the product already has 32 pubs

2023-02-22 09:19 UTC, guibescos requested changes
Need to handle case where there are 32 pubs

2023-02-22 09:22 UTC, cctdaniel commented on governance/xc_admin/packages/xc_admin_frontend/components/PermissionDepermissionKey.tsx
> +        if (product.metadata.asset_type === selectedAssetType) {
ah good catch

2023-02-22 09:46 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/components/PermissionDepermissionKey.tsx
> +          if (
Nit pick make it && statement instead of a double if statement

2023-02-22 09:48 UTC, guibescos requested changes
I think you need to handle the case where the publisher already exists for some price feeds. Similarly, only delete it from those price feeds where it is permissioned.

2023-02-23 08:41 UTC, guibescos approved these changes

2023-02-23 08:43 UTC, merged