[xc-admin] improve xc-admin-frontend UI/UX
pyth-network/pyth-crosschain pull request #673
Opened 2023-03-08 07:34 UTC by cctdaniel

2023-03-08 22:39 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/pages/index.tsx
> +          </StatusFilterProvider>
Why does the general tab need to be inside `StatusFilterProvider`

2023-03-08 22:46 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
> +    console.log(proposeSquads?.wallet.publicKey.toBase58())
console log

2023-03-08 22:47 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/components/tabs/General.tsx
> +        proposeSquads?.wallet,
mmm I don't think you need this `?`

2023-03-08 22:50 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/components/tabs/UpdatePermissions.tsx
> +        proposeSquads?.wallet,
No need for `?`

2023-03-08 22:54 UTC, guibescos commented on governance/xc_admin/packages/xc_admin_frontend/pages/index.tsx
> +    OPS_WALLET !== null
`OPS_WALLET ? (new NodeWallet(
          Keypair.fromSecretKey(Uint8Array.from(OPS_WALLET))
        ) as Wallet)` seems better style

2023-03-08 23:01 UTC, guibescos approved these changes
I feel like there are too many changes but lgtm.

2023-03-08 23:01 UTC, guibescos requested changes
Can you fix vercel preview

2023-03-08 23:09 UTC, guibescos reviewed
Typescript comments dropped

2023-03-09 02:01 UTC, cctdaniel commented on governance/xc_admin/packages/xc_admin_frontend/pages/index.tsx
> +        ) as Wallet)
yes

2023-03-09 04:42 UTC, merged