Pass Wormhole arguments from command line or env. vars
pyth-network/pyth-crosschain pull request #769
Opened 2023-04-18 19:30 UTC by thmzlt

- Format p2p.go
- Use lower port numbers by default
- Pass Wormhole arguments from command line or env. vars

2023-04-18 20:03 UTC, Reisen requested changes

2023-04-18 20:29 UTC, thmzlt commented on hermes/src/network/p2p.rs
> +        std::mem::forget(c_network_id);
For context, `forget` was used because the memory wasn't copied on the Go side until the goroutine spawned. Comment was just confusing.

2023-04-18 21:01 UTC, thmzlt commented on hermes/src/config.rs
> +        wh_bootstrap_addrs: String,
Good points. The downside is that it makes it harder to pass values using environment variables, but turns out that structopt supports it via https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.value_delimiter.

2023-04-19 09:10 UTC, Reisen commented on hermes/src/config.rs
> +        wh_bootstrap_addrs: String,
Oh nice, TIL, had not seen this option, and the help doc generated looks good.

2023-04-19 15:46 UTC, ali-bahjati approved these changes

2023-04-19 20:00 UTC, Reisen approved these changes

2023-04-19 20:04 UTC, merged